# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-12 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='file_size',
        ),
        migrations.AddField(
            model_name='uploads',
            name='upload_file',
            field=models.FileField(default=None, upload_to='storage/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploads',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
