# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-12 19:29
from __future__ import unicode_literals

import cloud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20161212_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='upload_file',
            field=models.FileField(upload_to=cloud.models.upload_file),
        ),
    ]
